export const UNIVERSITY_LIST_REQUEST = 'UNIVERSITY_LIST_REQUEST'
export const UNIVERSITY_LIST_SUCCESS = 'UNIVERSITY_LIST_SUCCESS'
export const UNIVERSITY_LIST_FAIL = 'UNIVERSITY_LIST_FAIL'

export const UNIVERSITY_PAGE_REQUEST = 'UNIVERSITY_PAGE_REQUEST'
export const UNIVERSITY_PAGE_SUCCESS = 'UNIVERSITY_PAGE_SUCCESS'
export const UNIVERSITY_PAGE_FAIL = 'UNIVERSITY_PAGE_FAIL'
